### ISSUE TITLE
[New Process Improvement Need]: Continuous Delivery

### ISSUE THREAD

**Issue by riverma** [NASA-AMMOS/slim#69]
### Checked for duplicates

Yes - I've already checked

### Category

Software Lifecycle - the creation, change, and release of software

### Describe the need

We have a need for best practices related to continuous delivery. Specifically, this means:
- Automatically publishing built artifacts to package managers / repositories. This includes:
  - Agreeing upon a set of package repositories based on the type of artifact: For example, PyPI for Python packages, DockerHub for Docker images, Maven for Java, etc. 
  - Agreeing upon a naming scheme to describe package namespaces within the repositories. For example, should we name artifacts `gov.nasa.jpl.<proj>.<package>` etc.?
  - Agreeing upon tiers of software packages to deliver, e.g. snapshots vs. versioned releases
  - Automation for GitHub-based repositories to automatically push built packages to repositories upon code commits
- A guide that walks through the above 

```[tasklist]
### Tasks
- [x] Recommendations on package repositories to use for type of software built
- [x] Recommendations on naming scheme to describe package namespaces
- [x] Recommendations on tiers of software packages to deliver
- [x] (Infusible artifact) GitHub Workflows that automatically push built software to a repository
- [x] A SLIM best practice guide
```
 
+1'd by @mike-gangl @mcduffie @LucaCinquini @kgrimes2

**Comment by riverma** [comment]
@jpl-jengelke recommends incorporating this into the current CI guide

**Comment by riverma** [comment]
+1'd by @ramesh-maddegoda (Unity, PDS)

**Comment by riverma** [comment]
# Recommendations
## Packages (Python)
![](https://api.linearity.io/icons/v1/thumbnails/python_Python_121464.png)
* **Suggested Repository**:
   * [PyPI](https://pypi.org)
* **Suggested Naming convention**
   * `nasa-[project org]-[module name] [semantic version ID]`
* **Known benefits**
   * Free
* **Known constraints**
   * 60MB file size limit, subject to increase by [PyPi-support](https://github.com/pypa/pypi-support)
## Packages (Java)
![](https://api.linearity.io/icons/v1/thumbnails/java_Java_13679.png)
* **Suggested Repository**:
   * [Maven Central](https://central.sonatype.com)
* **Suggested Naming convention**
   * `gov.nasa.[project org].[module name]`
* **Known benefits**
   * Free
   * No specific constraints to package size or volume 
* **Known constraints**
   * N/A
## Packages (NodeJS)
![](https://api.linearity.io/icons/v1/thumbnails/nodejs_Nodejs_54087.png)
* **Suggested Repository**:
   * [NPM Registry](https://www.npmjs.com) 
* **Suggested Naming convention**
   * `@nasa-[project org]/[module name]`
* **Known benefits**
   * Free
   * No specific constraints to package size or volume 
* **Known constraints**
   * Current NASA-branded packages vary in terms of account ownership and naming convention, potentially causing confusion
## Packages (Miscellaneous)
![](https://api.linearity.io/icons/v1/thumbnails/package_Breakable_12039.png)
* **Repository**:
   * Store in you Cloud-based VCS of choice (e.g. GitHub Releases, GitLab Package Registry)
* **Suggested Naming convention**
   * Semantic versioning: https://semver.org 
* **Known benefits**
   * Free
   * Unlimited number of packages
* **Known constraints**
   * Typically < 2GB individual package limit
   
## Infrastructure Deployments (Terraform)
![](https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_60,h_60/https://dashboard.snapcraft.io/site_media/appmedia/2017/05/logo-terraform-38bd0e32.png)
* **Repository**:
   * [Terraform Registry](https://registry.terraform.io)
* **Suggested Naming convention**
   * `terraform-nasa-[project org]-modules/[module-name]`
* **Known benefits**
   * Free
* **Known constraints**
   * No officially sponsored NASA namespace currently exists, potentially causing confusion
   * 1000 document limit per account
   * 500KB max file size per document 

## Test Data (Small < 2GB)
![](https://api.linearity.io/icons/v1/thumbnails/test_data_Test_Tube_42953.png)
* **Repository**:
   * Create a new repository in you Cloud-based VCS of choice (e.g. GitHub Releases, GitLab Package Registry)
* **Suggested Naming convention**
   * `[project org]-[project module]-test-dataset`
* **Known benefits**
   * Free
* **Known constraints**
   *  Typically < 2GB dataset limit

## Test Data (Large: 2GB - 100GB)
![](https://api.linearity.io/icons/v1/thumbnails/test_data_Test_Tube_42953.png)
* **Repository**:
   * [Amazon S3 Pre-signed URL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html)
* **Suggested Naming convention**
   * N/A
* **Known benefits**
   * Scalable storage
   * Authentication to rate-limit bandwidth usage
* **Known constraints**
   * Non-free

## Test Data (Large > 100GB)
![](https://api.linearity.io/icons/v1/thumbnails/test_data_Test_Tube_42953.png)
* **Repository**:
   * Earth-centric data: [EOSDIS Distributed Active Archive Centers (DAAC)](https://www.earthdata.nasa.gov/eosdis/daacs)
   * Planetary data: [Planetary Data System ](https://pds.nasa.gov)
* **Suggested Naming convention**
   * Determined by DAAC
* **Known benefits**
   * Free
* **Known constraints**
   * Requires project agreement and sponsorship

**Comment by drewm-jpl** [comment]
Hi @riverma,

Regarding repositories for test data, it might be worth looking at the data repository guidance provided by _Scientific Data - Nature_. In particular, the list of generalist data repositories may be pertinent.

https://www.nature.com/sdata/policies/repositories

**Comment by galenatjpl** [comment]
@riverma it looks like you have done a great job defining the repositories and formats that I would expect here.  I'm mostly familiar with Maven central, and PyPI from building things in the past.   

I think one thing to consider (which may be tangential to this ticket), is how/when do we push artifacts to these places?  We have sort of thought about some notional methodologies related to this (see the blue part of [this diagram](https://unity-sds.gitbook.io/docs/developer-docs/common-services/quick-start)).  

My thoughts about test data are that:
1). We will be hopefully centralizing on a single representative "golden dataset" that exercises the capabilities we care to test.
2). As such, we should probably just store that dataset in S3, and be done with it.  We aren't going to be storing gobs and gobs of data, but we just need that representative "starter" data.  Any data produced as a result of SPS runs can be transitory, and deleted relatively quickly after verification.    In other words, we aren't an actual mission, and won't had the Life Of Mission data requirements and associated costs.  If we need to store several gigabytes of data on S3, it's not going to break the bank.  

That being said, I haven't taken a look at the repositories @drewm-jpl mentioned.  I do know that we are all familiar with AWS/S3 though..

**Comment by galenatjpl** [comment]
Also, you might want to take a quick look at AWS CodeArtifact, but perhaps that wouldn't be the best solution to have work with a fully open-source building process.  Or maybe it would work?    Other public services like maven and pypi might be better, but just pointing out CodeArtifact, in case it wasn't looked at as part of this eval.

**Comment by riverma** [comment]
From @mike-gangl: see https://blog.pypi.org/posts/2023-04-23-introducing-pypi-organizations/

**Comment by yunks128** [comment]
@yunks128 
Next steps:
1. Finalize Repository and Naming Conventions
    - Several repository and naming conventions are outlined (e.g., PyPI, DockerHub, Maven).
    - Confirm and document the agreed-upon repository choices, especially for large datasets. Need to decide whether AWS CodeArtifact should be integrated or rejected.

2. Automation for CI/CD Pipeline
    - The primary need is to automate the build and push processes to the chosen repositories. GitHub Actions/Workflows is the suggested tool.
    - Create and share reusable workflow templates for common repositories like PyPI, Maven, and DockerHub.

3. Handling Large Test Data
    - You may centralize smaller test datasets (<2GB) in cloud-based version control systems (VCS) like GitHub Releases, but larger datasets need a solution, possibly using S3 or DAAC for Earth data.
    - Define a clear storage and retrieval strategy for both small and large test data, including cost considerations for S3. 
    - Set up scripts or workflows to handle dataset uploading, retention, and versioning.

4. Guide Creation
    - A SLIM best practices guide is needed to compile all the aforementioned strategies, repository decisions, automation workflows, and versioning schemes.
    - Draft the continuous delivery guide, starting with the repository, automation, and versioning steps. This guide can be integrated into the repository's docs folder.

5. Continuous Testing Integration
    - Since the continuous delivery process also involves ensuring that packages are tested before release, integrating a continuous testing strategy will strengthen the CD process.
    - Build upon the recent Continuous Testing Guide (#110) by linking the testing pipeline to the delivery pipeline, ensuring tests are automatically executed before artifacts are published.

**Comment by yunks128** [comment]
The first draft is here in progress: 
https://github.com/NASA-AMMOS/slim/blob/issue-69/docs/guides/software-lifecycle/continuous-delivery/readme.md

**Comment by hookhua** [comment]
Looks great for a first release. The initial example of `pypi-cd.yml` GitHub Actions Workflow for PyPI Project Continuous Delivery is very helpful as a reference example to get started.

Among the list of possible other repositories to provide examples for in future revisions, would a continuous delivery for ECR/DockerHub be next on the list for future iteration?

**Comment by yunks128** [comment]
@hookhua I'd like to move forward with iterating on the continuous delivery workflow for both DockerHub and Maven. Please share any relevant use cases or examples that we can explore and test to refine and optimize our approach!

**Comment by hookhua** [comment]
Anecdotally, many of the recent projects are delivering Docker artifacts as opposed to Java-only based artifacts. Would continuous delivery to DockerHub be of higher priority for folks? Am curious what others think?

**Comment by yunks128** [comment]
Dockerhub template: 

`.github/workflows/dockerhub-cd.yml`

```yaml
name: Docker Hub Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers to speed up builds
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/your-repository-name:latest
          ${{ secrets.DOCKER_USERNAME }}/your-repository-name:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    # Post the deployed image URL as an output
    - name: Output Docker image URL
      run: echo "Docker image URL: docker.io/${{ secrets.DOCKER_USERNAME }}/your-repository-name:latest"
```
